name: test_plan_manager_app
description: "App for testers"
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  path: ^1.9.1
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  dartz: ^0.10.1
  connectivity_plus: ^7.0.0
  shared_preferences: ^2.5.3
  go_router: ^16.3.0
  webview_flutter: ^4.13.0
  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  dio: ^5.9.0
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.1
  drift_local_storage_inspector: ^0.7.0
  storage_inspector: ^0.4.0
  mockito: ^5.5.1
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:

  uses-material-design: true
